apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webtest1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webtest1
    spec:
      containers:
      - name: web-test1
        image: asundara01/webtest1:v0.2
        ports:
        - containerPort: 80